import { useEffect, useState } from "react";
import type { ProjectSnapshot, StoryDetail, StorySummary } from "@ai-factory/contracts";

type View = "summary" | "backlog" | "runs" | "validations" | "config";
const emptyProject: ProjectSnapshot = { schemaVersion: 1, repository: { owner: "-", repo: "-", baseBranch: "-" }, controller: { available: false, version: "-" }, github: { connected: false, stale: true }, codex: { available: false }, counts: { total: 0, done: 0, blocked: 0, active: 0 } };

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers || {}) } });
  const value = await response.json() as { message?: string } & T;
  if (!response.ok) throw new Error(value.message || "Request failed");
  return value as T;
}

export function App() {
  const [view, setView] = useState<View>("summary");
  const [project, setProject] = useState(emptyProject);
  const [stories, setStories] = useState<StorySummary[]>([]);
  const [message, setMessage] = useState("Loading local controller…");
  const refresh = () => void Promise.all([api<ProjectSnapshot>("/api/project"), api<StorySummary[]>("/api/stories")]).then(([nextProject, nextStories]) => { setProject(nextProject); setStories(nextStories); setMessage(""); }).catch((error) => setMessage(error instanceof Error ? error.message : String(error)));
  useEffect(refresh, []);
  useEffect(() => { const events = new EventSource("/api/events"); events.onmessage = refresh; return () => events.close(); }, []);
  return <div className="app-shell"><header className="topbar"><div><p className="eyebrow">LOCAL SUPERVISION</p><h1>AI Factory</h1><p className="muted">{project.repository.owner}/{project.repository.repo} · {project.repository.baseBranch}</p></div><div className="topbar-status"><span className={`connection ${project.github.connected ? "good" : "muted"}`}>{project.github.connected ? "GitHub connected" : "GitHub offline"}</span><span className="session-label">Steve · local</span></div></header><nav className="tabs" aria-label="Main navigation">{(["summary", "backlog", "runs", "validations", "config"] as View[]).map((item) => <button className={view === item ? "tab active" : "tab"} onClick={() => setView(item)} key={item}>{navLabel(item)}</button>)}</nav>{message && <div className="notice" role="status">{message}</div>}<main>{view === "summary" && <Summary project={project} stories={stories} onNavigate={setView} />}{view === "backlog" && <Backlog stories={stories} />}{view === "runs" && <Runs project={project} />}{view === "validations" && <Validations stories={stories} />}{view === "config" && <Config />}</main></div>;
}

function navLabel(view: View): string { return ({ summary: "Overview", backlog: "Backlog", runs: "Executions", validations: "Human validation", config: "Configuration" })[view]; }
function Summary({ project, stories, onNavigate }: { project: ProjectSnapshot; stories: StorySummary[]; onNavigate: (view: View) => void }) { const active = stories.find((story) => ["ACTIVE", "PAUSE_REQUESTED", "PAUSED", "STOP_REQUESTED"].includes(story.executionStatus)); return <><section className="hero"><div><p className="eyebrow">CONTROL ROOM</p><h2>Know what is happening before you act.</h2><p className="hero-copy">The local controller keeps GitHub, Codex, worktrees, checks, and human decisions visible in one place.</p></div><button className="primary" onClick={() => onNavigate("runs")}>Open executions →</button></section><section className="cards"><Metric label="Stories done" value={`${project.counts.done}/${project.counts.total}`} detail="completed" /><Metric label="Active run" value={active?.storyId || "None"} detail={active ? active.executionStatus : "No execution"} /><Metric label="Blocked" value={String(project.counts.blocked)} detail={project.counts.blocked ? "needs attention" : "clear"} /><Metric label="CI health" value={project.github.connected ? "Connected" : "Offline"} detail={project.lastSyncAt ? `last sync ${formatDate(project.lastSyncAt)}` : "No sync yet"} /></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">LIVE CONTEXT</p><h3>{active ? `${active.storyId} · ${active.title}` : "No active execution"}</h3></div><span className="status-pill">{active?.validationStatus || "IDLE"}</span></div><p className="muted">{active?.blockedReason || "Start a run from the Executions view. Reading this dashboard never starts work."}</p></section><section className="diagnostics panel"><div className="panel-heading"><div><p className="eyebrow">SYSTEM STATUS</p><h3>Controller diagnostics</h3></div><span className="muted">{project.controller.available ? "Ready" : "Unavailable"}</span></div><div className="diagnostic-grid">{(project.diagnostics || []).map((item) => <div key={item.name} className="diagnostic"><strong>{item.name}</strong><span className={item.available ? "good-text" : "warning-text"}>{item.available ? "Available" : "Unavailable"}</span><small>{item.message}</small></div>)}</div></section></>; }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="metric"><span className="muted">{label}</span><strong>{value}</strong><small>{detail}</small></div>; }

function Backlog({ stories }: { stories: StorySummary[] }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [selected, setSelected] = useState<string>(); const [detail, setDetail] = useState<StoryDetail>(); const [loading, setLoading] = useState(false);
  const visible = stories.filter((story) => `${story.storyId} ${story.title}`.toLowerCase().includes(query.toLowerCase())).filter((story) => filter === "all" || (filter === "blocked" ? Boolean(story.blockedReason || story.dependencyError) : filter === "done" ? story.deliveryStatus === "MERGED" : filter === "active" ? ["ACTIVE", "PAUSE_REQUESTED", "PAUSED", "STOP_REQUESTED"].includes(story.executionStatus) : story.deliveryStatus === "NOT_STARTED"));
  const select = (storyId: string) => { setSelected(storyId); setLoading(true); void api<StoryDetail>(`/api/stories/${encodeURIComponent(storyId)}`).then(setDetail).catch(() => setDetail(undefined)).finally(() => setLoading(false)); };
  return <section><div className="section-heading"><div><p className="eyebrow">BACKLOG</p><h2>Stories and dependencies</h2><p className="muted">Manage user stories and let the runner do the work.</p></div><button className="primary" disabled>＋ New story</button></div><div className="backlog-layout"><div className="backlog-list"><div className="filters"><input aria-label="Search stories" placeholder="Search stories…" value={query} onChange={(event) => setQuery(event.target.value)} /><select aria-label="Filter stories" value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">All states</option><option value="pending">Pending</option><option value="active">Active</option><option value="blocked">Blocked</option><option value="done">Done</option></select></div><div className="story-list">{visible.length ? visible.map((story) => <button className={`story-row story-button ${selected === story.storyId ? "selected" : ""}`} key={story.storyId} onClick={() => select(story.storyId)}><div><span className="eyebrow">{story.storyId} · P{story.priority}</span><h3>{story.title}</h3><p className="muted">Depends on {story.dependencies.length ? story.dependencies.join(", ") : "nothing"}</p></div><div className="story-meta"><span className="status-pill">{statusLabel(story)}</span><span className="muted">{story.validationStatus}</span></div></button>) : <div className="empty">No stories match this filter.</div>}</div></div><div className="detail-panel panel">{loading && <p className="muted">Loading story…</p>}{!loading && detail && <StoryDetailPanel detail={detail} />}{!loading && !detail && <div className="empty"><strong>Select a story</strong><p>Choose a backlog row to inspect its specification and evidence.</p></div>}</div></div></section>;
}

function StoryDetailPanel({ detail }: { detail: StoryDetail }) { return <div><div className="panel-heading"><div><span className="eyebrow">{detail.storyId}</span><h3>{detail.title}</h3></div><span className="status-pill">{statusLabel(detail)}</span></div><p>{detail.objective}</p><div className="detail-tabs"><span className="active">Overview</span><span>Commits</span><span>Pull request</span><span>Timeline</span></div><h4>Acceptance criteria <span className="muted">{detail.acceptanceCriteria.length}</span></h4><ul className="criteria-list">{detail.acceptanceCriteria.length ? detail.acceptanceCriteria.map((criterion) => <li key={criterion}>✓ {criterion}</li>) : <li className="muted">No criteria found in the specification.</li>}</ul><h4>Dependencies</h4><p className={detail.dependencyError ? "warning-text" : "muted"}>{detail.dependencyError || (detail.dependencies.length ? detail.dependencies.join(", ") : "None")}</p><div className="link-row">{detail.issueUrl && <a href={detail.issueUrl} target="_blank" rel="noreferrer">Issue #{detail.githubIssueNumber} ↗</a>}{detail.pullRequestUrl && <a href={detail.pullRequestUrl} target="_blank" rel="noreferrer">PR #{detail.pullRequestNumber} ↗</a>}{!detail.issueUrl && !detail.pullRequestUrl && <span className="muted">No Issue or PR linked</span>}</div><details><summary>Specification source</summary><pre className="markdown-source">{detail.markdown}</pre></details>{detail.conflict && <div className="notice">Specification conflict: {detail.conflict.summary}</div>}</div>; }

function Runs({ project }: { project: ProjectSnapshot }) { const [busy, setBusy] = useState(false); const [runId, setRunId] = useState(project.activeRunId); const [error, setError] = useState(""); const act = async (path: string, body?: unknown) => { setBusy(true); setError(""); try { const run = await api<{ runId: string }>(path, { method: "POST", body: body ? JSON.stringify(body) : undefined }); if (run.runId) setRunId(run.runId); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } }; return <section><div className="section-heading"><div><p className="eyebrow">EXECUTIONS</p><h2>Start and control work</h2></div><span className="status-pill">{runId ? "RUN AVAILABLE" : "IDLE"}</span></div><div className="panel run-panel"><p className="muted">A page load never starts an execution. Actions are reflected only after the controller confirms them.</p>{error && <div className="notice">{error}</div>}{runId ? <div className="button-row"><button disabled={busy} onClick={() => void act(`/api/runs/${runId}/pause`)}>Request pause</button><button disabled={busy} onClick={() => void act(`/api/runs/${runId}/stop`)}>Stop</button><button disabled={busy} onClick={() => void act(`/api/runs/${runId}/resume`)}>Resume</button></div> : <><label>Maximum stories <input type="number" min="1" defaultValue="1" id="max-stories" /></label><button className="primary" disabled={busy} onClick={() => void act("/api/runs", { maxStories: Number((document.getElementById("max-stories") as HTMLInputElement).value), autoMerge: false })}>Start one story</button></>}</div></section>; }
function Validations({ stories }: { stories: StorySummary[] }) { return <section><div className="section-heading"><div><p className="eyebrow">VALIDATION</p><h2>Evidence, not just color</h2></div></div><div className="story-list">{stories.map((story) => <article className="story-row" key={story.storyId}><div><h3>{story.storyId} · {story.title}</h3><p className="muted">Delivery {story.deliveryStatus} · SHA {story.headSha || "not available"}</p></div><span className="status-pill">{story.validationStatus}</span></article>)}{!stories.length && <div className="empty">No validation evidence yet.</div>}</div></section>; }
function Config() { return <section><div className="section-heading"><div><p className="eyebrow">CONFIGURATION</p><h2>Trusted settings</h2></div></div><div className="panel"><p className="muted">Configuration editing is deliberately gated behind the versioned backend adapter. Credentials never belong in this form.</p><p>Use the local <code>automation/config.json</code> for the current pilot configuration. The UI will show effective revisions here as the configuration adapter is enabled.</p></div></section>; }
function statusLabel(story: Pick<StorySummary, "deliveryStatus" | "executionStatus" | "blockedReason" | "dependencyError">): string { if (story.deliveryStatus === "MERGED") return "DONE"; if (story.blockedReason || story.dependencyError) return "BLOCKED"; if (["ACTIVE", "PAUSE_REQUESTED", "PAUSED", "STOP_REQUESTED"].includes(story.executionStatus)) return "RUNNING"; return "READY"; }
function formatDate(value: string): string { return new Date(value).toLocaleString(); }
